#!/bin/bash
# Rolle's dynamic motd
# Symlink this file to /usr/bin/dynmotd and add it to your ~/.bash_profile
# Set in /usr/ssh/sshd_config:

# PrintMotd no
# PrintLastLog no

# Set up colors:
NO_COLOR='\e[0m' # Disable any colors
# regular colors
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'
BLUE='\e[0;34m'
MAGENTA='\e[0;35m'
CYAN='\e[0;36m'
WHITE='\e[0;37m'
# Emphasized (bolded) colors
EBLACK='\e[1;30m'
ERED='\e[1;31m'
EGREEN='\e[1;32m'
EYELLOW='\e[1;33m'
EBLUE='\e[1;34m'
EMAGENTA='\e[1;35m'
ECYAN='\e[1;36m'
EWHITE='\e[1;37m'
# Underlined colors
UBLACK='\e[4;30m'
URED='\e[4;31m'
UGREEN='\e[4;32m'
UYELLOW='\e[4;33m'
UBLUE='\e[4;34m'
UMAGENTA='\e[4;35m'
UCYAN='\e[4;36m'
UWHITE='\e[4;37m'
# Background colors
BBLACK='\e[40m'
BRED='\e[41m'
BGREEN='\e[42m'
BYELLOW='\e[43m'
BBLUE='\e[44m'
BMAGENTA='\e[45m'
BCYAN='\e[46m'
BWHITE='\e[47m'

echo -e "
$ECYAN`figlet -f /usr/share/figlet/fonts/contessa.flf " peikko"`

 $ECYAN peikko.us 
 $CYAN powered by `cat /etc/redhat-release |head -1`
 $CYAN _________________________________________

 $CYAN uptime: $CYAN`/usr/bin/better_uptime`.$NO_COLOR
 $CYAN memory: $CYAN`cat /proc/meminfo | grep MemFree | awk {'print int($2/1000)'}` MB vapaana / `cat /proc/meminfo | grep MemTotal | awk {'print int($2/1000)'}` MB$NO_COLOR
 $CYAN processes: $CYAN`cat /proc/loadavg | cut -d"/" -f2| cut -d" " -f1`$NO_COLOR"

echo -e "$ERED

 !important$EWHITE" 

if ps ax | grep -v grep | grep irssi > /dev/null
then
echo -e " \e[1;37mirssi             :$EGREEN active     $EWHITE tmux a"
else
echo -e " \e[1;37mirssi             :$ERED off        $EWHITE tmux"
fi

if ps ax | grep -v grep | grep CouchPotato > /dev/null
then
echo -e " \e[1;37mCouchPotatoServer :$EGREEN active     $EWHITE /home/rolle/CouchPotatoServer/CouchPotato.py --debug"
else
echo -e " \e[1;37mCouchPotatoServer :$ERED off        $EWHITE python /home/rolle/CouchPotatoServer/CouchPotato.py --debug"
fi

if ps ax | grep -v grep | grep dropbox > /dev/null
then
echo -e " \e[1;37mDropbox           :$EGREEN active     $EWHITE ~/bin/dropbox.py"
else
echo -e " \e[1;37mDropbox           :$ERED off        $EWHITE ~/bin/dropbox.py start"
fi

if ps ax | grep -v grep | grep denyhosts > /dev/null
then
echo -e " \e[1;37mdenyhosts         :$EGREEN active     $EWHITE /etc/rc.d/denyhosts"
else
echo -e " \e[1;37mdenyhosts         :$ERED off        $EWHITE roottina: service denyhosts start"
fi

if ps ax | grep -v grep | grep sysmonserver > /dev/null
then
echo -e " \e[1;37msysmonserver      :$EGREEN active     $EWHITE /var/sysmon-ws/sysmonserver.py"
else
echo -e " \e[1;37msysmonserver      :$ERED off        $EWHITE python /var/sysmon-ws/sysmonserver.py >/dev/null&"
fi

if ps ax | grep -v grep | grep subsonic > /dev/null
then
echo -e " \e[1;37msubsonic          :$EGREEN active     $EWHITE sh /var/subsonic/subsonic.sh"
else
echo -e " \e[1;37msubsonic          :$ERED off        $EWHITE sh /var/subsonic/subsonic.sh"
fi

echo -e "$NO_COLOR"
