--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer
--disable-features=WaylandFractionalScaleV1,UseChromeOSDirectVideoDecoder
--password-store=basic
--disable-gpu-memory-buffer-video-frames
--use-gl=angle
--use-angle=gl
--canvas-oop-rasterization
--disable-background-networking
--disable-component-update
