preload = /home/rolle/Nextcloud/Wallpapers/artofgregmartin.com/6603aa91eff828b1908237a1_minimalist-arch-11.jpg
wallpaper = ,/home/rolle/Nextcloud/Wallpapers/artofgregmartin.com/6603aa91eff828b1908237a1_minimalist-arch-11.jpg
splash = false
